services:
  app:
    image: ghcr.io/digozi/milestone-staging:0.0.3
    environment:
      - PORT=5001
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - TRADING_212_API_KEY=${TRADING_212_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - EODHD_API_KEY=${EODHD_API_KEY}
    ports:
      - 5001:5001
